# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 16:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160116_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 16, 16, 1, 54, 193392, tzinfo=utc)),
        ),
    ]
